#!/bin/bash
set -e

ARTIFACT=target/scala-*/konstructs-server-assembly-*.jar
API_URL=https://api.bintray.com
API_AUTH=-unsg:$bintray_api_key

# Upload master to bintray
if [ "x$TRAVIS_BRANCH" == "xmaster" ] && [ "x$TRAVIS_PULL_REQUEST" == "xfalse" ]; then
	curl -X DELETE $API_AUTH $API_URL/packages/konstructs/jars/server/versions/dev
	curl -T $ARTIFACT $API_AUTH $API_URL/content/konstructs/jars/server/dev/konstructs-server-build-dev.jar
	curl -X POST -unsg:$bintray_api_key $API_URL/content/konstructs/jars/server/dev/publish
	echo | nc craft.nsg.cc 44711
fi

# Upload tagged releases to bintray
if [ $TRAVIS_TAG ]; then
	# Release downloadable JAR
	curl -T $ARTIFACT $API_AUTH $API_URL/content/konstructs/jars/server/$TRAVIS_TAG/konstructs-server-build-$TRAVIS_TAG.jar
	curl -X POST -unsg:$bintray_api_key $API_URL/content/konstructs/jars/server/$TRAVIS_TAG/publish
	# Release to maven repository
	mkdir -p ~/.bintray
	cat <<END > ~/.bintray/.credentials
realm = Bintray API Realm
host = api.bintray.com
user = nsg
password = $bintray_api_key
END
	sbt -batch publish
fi
