#!/bin/bash
set -e

ARTIFACT=target/scala-*/craft-server-assembly-*.jar
API_URL=https://api.bintray.com
API_AUTH=-unsg:$bintray_api_key

# Upload master to bintray
if [ "x$TRAVIS_BRANCH" == "xmaster" ] && [ "x$TRAVIS_PULL_REQUEST" == "xfalse" ]; then
	curl -X DELETE $API_AUTH $API_URL/packages/nsg/craft/craft-server/versions/dev
	curl -T $ARTIFACT $API_AUTH $API_URL/content/nsg/craft/craft-server/dev/craft-server-build-dev.jar
	curl -X POST -unsg:$bintray_api_key $API_URL/content/nsg/craft/craft-server/dev/publish
	echo | nc craft.nsg.cc 44711
fi

# Upload tagged releases to bintray
if [ $TRAVIS_TAG ]; then
	curl -T $ARTIFACT $API_AUTH $API_URL/content/nsg/craft/craft-server/$TRAVIS_TAG/craft-server-build-$TRAVIS_TAG.jar
	curl -X POST -unsg:$bintray_api_key $API_URL/content/nsg/craft/craft-server/$TRAVIS_TAG/publish
fi
