package konstructs.api;

import java.io.Serializable;
import java.util.Arrays;

/**
 * BlockType is a class that holds all relevant information regarding
 * a block's type. Instances of this class is generated when the
 * server is started from the server configuration. It is immutable
 * and serializable.
 */
public final class BlockType implements Serializable {
    public static final String SHAPE_BLOCK = "block";
    public static final String SHAPE_PLANT = "plant";

    private final int[] faces;
    private final String shape;
    private final boolean obstacle;
    private final boolean transparent;

    /**
     * Constructs an immutable BlockType.
     * @param faces the texture index for all faces of a BlockType
     * @param shape the shape of the block
     * @param obstacle is this BlockType an obstacle?
     * @param transparent is this BlockType transparent?
     * @see #getFaces
     * @see #getShape
     * @see #isObstacle
     * @see #isTransparent
     */
    public BlockType(int[] faces, String shape, boolean obstacle, boolean transparent) {
        if(!(shape.equals(BlockType.SHAPE_BLOCK) || shape.equals(BlockType.SHAPE_PLANT)))
            throw new IllegalArgumentException("The shape must be either \"" +
                                               BlockType.SHAPE_BLOCK +
                                               "\" or \"" +
                                               BlockType.SHAPE_PLANT +
                                               "\"");
        this.faces = faces;
        this.shape = shape;
        this.obstacle = obstacle;
        this.transparent = transparent;
    }

    /**
     * Returns the texture indexes for this block type. A texture index
     * is an index generated by the server for the position at which
     * the texture for each of the block's faces is stored.
     * @return the array containing the texture indexes for this block type
     */
    public int[] getFaces() {
        return faces;
    }

    /**
     * Returns the shape of this block type. The shape of the block can
     * currently only be either of <code>BlockType.SHAPE_BLOCK</code> or
     * <code>BlockType.SHAPE_PLANT</code>.
     * @return the shape of the block
     */
    public String getShape() {
        return shape;
    }

    /**
     * Checks if this block type is seen as an obstacle or not. A block with
     * an obstacle type can not be passed through by the player.
     * @return true if this block is an obstacle, otherwise false
     */
    public boolean isObstacle() {
        return obstacle;
    }

    /**
     * Checks if this block type is seen as transparent by the player.
     * @return true if this block is transparent otherwise false
     */
    public boolean isTransparent() {
        return transparent;
    }

    /**
     * Returns a copy with a new value for the faces
     * field.
     * @param faces the new value for faces
     * @return the copy
     * @see #getFaces
     */
    public BlockType withFaces(int[] faces) {
        return new BlockType(faces, shape, obstacle, transparent);
    }

    /**
     * Returns a copy with a new value for the shape
     * field.
     * @param shape the new value for shape
     * @return the copy
     * @see #getShape
     */
    public BlockType withShape(String shape) {
        return new BlockType(faces, shape, obstacle, transparent);
    }

    /**
     * Returns a copy with a new value for the obstacle
     * field.
     * @param obstacle the new value for obstacle
     * @return the copy
     * @see #isObstacle
     */
    public BlockType withObstacle(boolean obstacle) {
        return new BlockType(faces, shape, obstacle, transparent);
    }

    /**
     * Returns a copy with a new value for the transparent
     * field.
     * @param transparent the new value for transparent
     * @return the copy
     * @see #isTransparent
     */
    public BlockType withTransparent(boolean transparent) {
        return new BlockType(faces, shape, obstacle, transparent);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        BlockType blockType = (BlockType) o;

        if (obstacle != blockType.obstacle) return false;
        if (transparent != blockType.transparent) return false;
        if (!Arrays.equals(faces, blockType.faces)) return false;
        return shape.equals(blockType.shape);

    }

    @Override
    public int hashCode() {
        int result = Arrays.hashCode(faces);
        result = 31 * result + shape.hashCode();
        result = 31 * result + (obstacle ? 1 : 0);
        result = 31 * result + (transparent ? 1 : 0);
        return result;
    }

    @Override
    public String toString() {
        return "BlockType(" +
                "faces=" + Arrays.toString(faces) +
                ", shape='" + shape + '\'' +
                ", obstacle=" + obstacle +
                ", transparent=" + transparent +
                ')';
    }
}
